// <auto-generated />
using System;
using HCMS4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCMS4.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505120000_AddMissingTables")]
    partial class AddMissingTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HCMS4.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("HCMS4.Models.Appointment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<int>("DoctorId")
                    .HasColumnType("int");

                b.Property<DateTime>("AppointmentDateTime")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("PatientId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Status")
                    .HasColumnType("nvarchar(max)");

                b.Property<double?>("NoShowRiskScore")
                    .HasColumnType("float");

                b.Property<bool>("WasNoShow")
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<DateTime?>("NoShowEvaluatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("DoctorId");

                b.HasIndex("PatientId");

                b.ToTable("Appointments");
            });

            modelBuilder.Entity("HCMS4.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("HCMS4.Models.ClinicalNote", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("DoctorId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("NoteText")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("PatientId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("DoctorId");

                b.HasIndex("PatientId");

                b.ToTable("ClinicalNotes");
            });

            modelBuilder.Entity("HCMS4.Models.Complaint", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<string>("AttachmentPath")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<int>("PatientId")
                    .HasColumnType("int");

                b.Property<DateTime>("ResolvedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("ResolutionNotes")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<DateTime>("SubmissionDate")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("TrackingNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("PatientId");

                b.ToTable("Complaints");
            });

            modelBuilder.Entity("HCMS4.Models.DailyReport", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<string>("DoctorId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Notes")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("PatientId")
                    .HasColumnType("int");

                b.Property<int>("PrescriptionId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("DoctorId");

                b.HasIndex("PatientId");

                b.HasIndex("PrescriptionId");

                b.ToTable("DailyReports");
            });

            modelBuilder.Entity("HCMS4.Models.Doctor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<decimal>("AverageRating")
                    .HasColumnType("decimal(3,2)");

                b.Property<string>("ChronicConditions")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CreatedByUserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("EmergencyContact")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsAvailable")
                    .HasColumnType("bit");

                b.Property<bool>("CanPublishArticles")
                    .HasColumnType("bit");

                b.Property<int?>("SpecializationId")
                    .HasColumnType("int");

                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("SpecializationId");

                b.HasIndex("UserId")
                    .IsUnique()
                    .HasFilter("[UserId] IS NOT NULL");

                b.ToTable("Doctors");
            });

            modelBuilder.Entity("HCMS4.Models.DoctorLeave", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DoctorId")
                    .HasColumnType("int");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<int>("LeaveType")
                    .HasColumnType("int");

                b.Property<string>("Notes")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("DoctorId");

                b.ToTable("DoctorLeaves");
            });

            modelBuilder.Entity("HCMS4.Models.DoctorReviewRequest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<string>("AdditionalComments")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<int>("DoctorId")
                    .HasColumnType("int");

                b.Property<string>("DoctorResponse")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<int>("PharmacistId")
                    .HasColumnType("int");

                b.Property<int>("PrescriptionId")
                    .HasColumnType("int");

                b.Property<DateTime>("RequestDate")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<int>("ReasonForReview")
                    .HasColumnType("int");

                b.Property<DateTime>("ReviewedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("SuggestedAlternative")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.HasKey("Id");

                b.HasIndex("DoctorId");

                b.HasIndex("PharmacistId");

                b.HasIndex("PrescriptionId");

                b.ToTable("DoctorReviewRequests");
            });

            modelBuilder.Entity("HCMS4.Models.Drug", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<string>("BatchNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<DateTime>("ExpiryDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<decimal>("SellingPrice")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Supplier")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("UnitPrice")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.ToTable("Drugs");
            });

            modelBuilder.Entity("HCMS4.Models.Invoice", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<int?>("AppointmentId")
                    .HasColumnType("int");

                b.Property<decimal>("ConsultationFee")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime>("InvoiceDate")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<decimal>("MedicationTotal")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("PatientId")
                    .HasColumnType("int");

                b.Property<int?>("PrescriptionId")
                    .HasColumnType("int");

                b.Property<decimal>("TotalAmount")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("AppointmentId");

                b.HasIndex("PatientId");

                b.HasIndex("PrescriptionId");

                b.ToTable("Invoices");
            });

            modelBuilder.Entity("HCMS4.Models.LeaveRequest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("DoctorId")
                    .HasColumnType("int");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<int>("LeaveType")
                    .HasColumnType("int");

                b.Property<string>("Reason")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("DoctorId");

                b.ToTable("LeaveRequests");
            });

            modelBuilder.Entity("HCMS4.Models.MedicalArticle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<string>("Category")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<int>("DoctorId")
                    .HasColumnType("int");

                b.Property<DateTime>("PublishedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("Summary")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.HasIndex("DoctorId");

                b.ToTable("MedicalArticles");
            });

            modelBuilder.Entity("HCMS4.Models.Patient", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<string>("ChronicConditions")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("DisabledAt")
                    .HasColumnType("datetime2");

                b.Property<string>("DisableReason")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EmergencyContact")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("LastVisit")
                    .HasColumnType("datetime2");

                b.Property<int>("NoShowCount")
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<int>("Status")
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId")
                    .IsUnique()
                    .HasFilter("[UserId] IS NOT NULL");

                b.ToTable("Patients");
            });

            modelBuilder.Entity("HCMS4.Models.Pharmacist", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<string>("FullName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId")
                    .IsUnique()
                    .HasFilter("[UserId] IS NOT NULL");

                b.ToTable("Pharmacists");
            });

            modelBuilder.Entity("HCMS4.Models.PharmacistPrescriptionNote", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<bool>("NotifyDoctor")
                    .HasColumnType("bit");

                b.Property<string>("NoteText")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<int>("PharmacistId")
                    .HasColumnType("int");

                b.Property<int>("PrescriptionId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("PharmacistId");

                b.HasIndex("PrescriptionId");

                b.ToTable("PharmacistPrescriptionNotes");
            });

            modelBuilder.Entity("HCMS4.Models.Prescription", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<int?>("AppointmentId")
                    .HasColumnType("int");

                b.Property<decimal>("ConsultationFee")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("DoctorId")
                    .HasColumnType("int");

                b.Property<decimal>("MedicationTotal")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Notes")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("PatientId")
                    .HasColumnType("int");

                b.Property<DateTime>("PrescriptionDate")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<DateTime?>("PrescriptionExpiryDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("AppointmentId");

                b.HasIndex("DoctorId");

                b.HasIndex("PatientId");

                b.ToTable("Prescriptions");
            });

            modelBuilder.Entity("HCMS4.Models.PrescriptionItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<int>("DrugId")
                    .HasColumnType("int");

                b.Property<int>("PrescriptionId")
                    .HasColumnType("int");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("DrugId");

                b.HasIndex("PrescriptionId");

                b.ToTable("PrescriptionItems");
            });

            modelBuilder.Entity("HCMS4.Models.PrescriptionReissueRequest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<int>("DoctorId")
                    .HasColumnType("int");

                b.Property<int>("PatientId")
                    .HasColumnType("int");

                b.Property<int>("PrescriptionId")
                    .HasColumnType("int");

                b.Property<DateTime>("RequestDate")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<DateTime>("ReviewedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("DoctorResponse")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("DoctorId");

                b.HasIndex("PatientId");

                b.HasIndex("PrescriptionId");

                b.ToTable("PrescriptionReissueRequests");
            });

            modelBuilder.Entity("HCMS4.Models.PurchaseRequest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("CreatedByPharmacistId")
                    .HasColumnType("int");

                b.Property<string>("RejectionReason")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CreatedByPharmacistId");

                b.ToTable("PurchaseRequests");
            });

            modelBuilder.Entity("HCMS4.Models.PurchaseRequestItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<int>("DrugId")
                    .HasColumnType("int");

                b.Property<int>("PurchaseRequestId")
                    .HasColumnType("int");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("DrugId");

                b.HasIndex("PurchaseRequestId");

                b.ToTable("PurchaseRequestItems");
            });

            modelBuilder.Entity("HCMS4.Models.Specialization", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<decimal>("ConsultationFee")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Specializations");
            });

            modelBuilder.Entity("HCMS4.Models.Survey", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<string>("CreatedByUserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<int>("TargetAudience")
                    .HasColumnType("int");

                b.Property<string>("TargetCriteria")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.HasIndex("CreatedByUserId");

                b.ToTable("Surveys");
            });

            modelBuilder.Entity("HCMS4.Models.SurveyAnswer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<int>("BooleanValue")
                    .HasColumnType("bit");

                b.Property<int>("NumericValue")
                    .HasColumnType("int");

                b.Property<string>("AnswerText")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<int>("SurveyAssignmentId")
                    .HasColumnType("int");

                b.Property<int>("SurveyQuestionId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("SurveyAssignmentId");

                b.HasIndex("SurveyQuestionId");

                b.ToTable("SurveyAnswers");
            });

            modelBuilder.Entity("HCMS4.Models.SurveyAssignment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<DateTime>("AssignedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<DateTime>("CompletedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("PatientId")
                    .HasColumnType("int");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<int>("SurveyId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("PatientId");

                b.HasIndex("SurveyId");

                b.HasIndex("SurveyId", "PatientId")
                    .IsUnique();

                b.ToTable("SurveyAssignments");
            });

            modelBuilder.Entity("HCMS4.Models.SurveyQuestion", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<bool>("IsRequired")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("QuestionText")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<int>("QuestionType")
                    .HasColumnType("int");

                b.Property<int>("SurveyId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("SurveyId");

                b.ToTable("SurveyQuestions");
            });

            modelBuilder.Entity("HCMS4.Models.SurveyQuestionOption", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<string>("OptionText")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int>("SurveyQuestionId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("SurveyQuestionId");

                b.ToTable("SurveyQuestionOptions");
            });

            modelBuilder.Entity("HCMS4.Models.SystemActivityLog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("ActivityType")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<string>("IpAddress")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("RelatedEntityId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("SystemActivityLogs");
            });

            modelBuilder.Entity("HCMS4.Models.UserNotification", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<bool>("IsRead")
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<string>("Message")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("RelatedEntityId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.HasIndex("UserId", "IsRead");

                b.ToTable("UserNotifications");
            });

            modelBuilder.Entity("HCMS4.Models.VisitRating", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");

                b.Property<int>("AppointmentId")
                    .HasColumnType("int");

                b.Property<int>("DoctorId")
                    .HasColumnType("int");

                b.Property<int>("PatientId")
                    .HasColumnType("int");

                b.Property<string>("Comment")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<int>("Rating")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<bool?>("DoctorCooperative")
                    .HasColumnType("bit");

                b.Property<bool?>("WaitingTimeReasonable")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.HasIndex("AppointmentId");

                b.HasIndex("DoctorId");

                b.HasIndex("PatientId");

                b.ToTable("VisitRatings");
            });

            modelBuilder.Entity("HCMS4.Models.Appointment", b =>
            {
                b.HasOne("HCMS4.Models.Doctor", "Doctor")
                    .WithMany("Appointments")
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Patient", "Patient")
                    .WithMany("Appointments")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("HCMS4.Models.ClinicalNote", b =>
            {
                b.HasOne("HCMS4.Models.Doctor", "Doctor")
                    .WithMany()
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("HCMS4.Models.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.Complaint", b =>
            {
                b.HasOne("HCMS4.Models.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.DailyReport", b =>
            {
                b.HasOne("HCMS4.Models.Doctor", "Doctor")
                    .WithMany()
                    .HasForeignKey("DoctorId");

                b.HasOne("HCMS4.Models.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Prescription", "Prescription")
                    .WithMany()
                    .HasForeignKey("PrescriptionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.Doctor", b =>
            {
                b.HasOne("HCMS4.Models.Specialization", "Specialization")
                    .WithMany("Doctors")
                    .HasForeignKey("SpecializationId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("HCMS4.Models.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId");
            });

            modelBuilder.Entity("HCMS4.Models.DoctorLeave", b =>
            {
                b.HasOne("HCMS4.Models.Doctor", "Doctor")
                    .WithMany("DoctorLeaves")
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.DoctorReviewRequest", b =>
            {
                b.HasOne("HCMS4.Models.Doctor", "Doctor")
                    .WithMany()
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Pharmacist", "Pharmacist")
                    .WithMany()
                    .HasForeignKey("PharmacistId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Prescription", "Prescription")
                    .WithMany()
                    .HasForeignKey("PrescriptionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.Invoice", b =>
            {
                b.HasOne("HCMS4.Models.Appointment", "Appointment")
                    .WithMany()
                    .HasForeignKey("AppointmentId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("HCMS4.Models.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Prescription", "Prescription")
                    .WithMany()
                    .HasForeignKey("PrescriptionId")
                    .OnDelete(DeleteBehavior.SetNull);
            });

            modelBuilder.Entity("HCMS4.Models.LeaveRequest", b =>
            {
                b.HasOne("HCMS4.Models.Doctor", "Doctor")
                    .WithMany()
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.MedicalArticle", b =>
            {
                b.HasOne("HCMS4.Models.Doctor", "Doctor")
                    .WithMany("MedicalArticles")
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.Patient", b =>
            {
                b.HasOne("HCMS4.Models.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId");
            });

            modelBuilder.Entity("HCMS4.Models.Pharmacist", b =>
            {
                b.HasOne("HCMS4.Models.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId");
            });

            modelBuilder.Entity("HCMS4.Models.PharmacistPrescriptionNote", b =>
            {
                b.HasOne("HCMS4.Models.Pharmacist", "Pharmacist")
                    .WithMany()
                    .HasForeignKey("PharmacistId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Prescription", "Prescription")
                    .WithMany()
                    .HasForeignKey("PrescriptionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.Prescription", b =>
            {
                b.HasOne("HCMS4.Models.Appointment", "Appointment")
                    .WithMany()
                    .HasForeignKey("AppointmentId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("HCMS4.Models.Doctor", "Doctor")
                    .WithMany()
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Patient", "Patient")
                    .WithMany("Prescriptions")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.PrescriptionItem", b =>
            {
                b.HasOne("HCMS4.Models.Drug", "Drug")
                    .WithMany("PrescriptionItems")
                    .HasForeignKey("DrugId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Prescription", "Prescription")
                    .WithMany("PrescriptionItems")
                    .HasForeignKey("PrescriptionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.PrescriptionReissueRequest", b =>
            {
                b.HasOne("HCMS4.Models.Doctor", "Doctor")
                    .WithMany()
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Prescription", "Prescription")
                    .WithMany()
                    .HasForeignKey("PrescriptionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.PurchaseRequest", b =>
            {
                b.HasOne("HCMS4.Models.Pharmacist", "CreatedByPharmacist")
                    .WithMany()
                    .HasForeignKey("CreatedByPharmacistId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.PurchaseRequestItem", b =>
            {
                b.HasOne("HCMS4.Models.Drug", "Drug")
                    .WithMany()
                    .HasForeignKey("DrugId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HCMS4.Models.PurchaseRequest", "PurchaseRequest")
                    .WithMany("Items")
                    .HasForeignKey("PurchaseRequestId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.Survey", b =>
            {
                b.HasOne("HCMS4.Models.ApplicationUser", "CreatedByUser")
                    .WithMany()
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("HCMS4.Models.SurveyAnswer", b =>
            {
                b.HasOne("HCMS4.Models.SurveyAssignment", "SurveyAssignment")
                    .WithMany("Answers")
                    .HasForeignKey("SurveyAssignmentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HCMS4.Models.SurveyQuestion", "SurveyQuestion")
                    .WithMany("Answers")
                    .HasForeignKey("SurveyQuestionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.SurveyAssignment", b =>
            {
                b.HasOne("HCMS4.Models.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Survey", "Survey")
                    .WithMany("Assignments")
                    .HasForeignKey("SurveyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.SurveyQuestion", b =>
            {
                b.HasOne("HCMS4.Models.Survey", "Survey")
                    .WithMany("Questions")
                    .HasForeignKey("SurveyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.SurveyQuestionOption", b =>
            {
                b.HasOne("HCMS4.Models.SurveyQuestion", "SurveyQuestion")
                    .WithMany("Options")
                    .HasForeignKey("SurveyQuestionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.SystemActivityLog", b =>
            {
                b.HasOne("HCMS4.Models.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("HCMS4.Models.UserNotification", b =>
            {
                b.HasOne("HCMS4.Models.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.VisitRating", b =>
            {
                b.HasOne("HCMS4.Models.Appointment", "Appointment")
                    .WithMany()
                    .HasForeignKey("AppointmentId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Doctor", "Doctor")
                    .WithMany()
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HCMS4.Models.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HCMS4.Models.Specialization", b =>
            {
                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "Cardiology",
                        ConsultationFee = 150m,
                        IsActive = true,
                        Description = "قلبية"
                    },
                    new
                    {
                        Id = 2,
                        Name = "Dermatology",
                        ConsultationFee = 120m,
                        IsActive = true,
                        Description = "جلدية"
                    },
                    new
                    {
                        Id = 3,
                        Name = "Orthopedics",
                        ConsultationFee = 130m,
                        IsActive = true,
                        Description = "عظمية"
                    },
                    new
                    {
                        Id = 4,
                        Name = "Neurology",
                        ConsultationFee = 180m,
                        IsActive = true,
                        Description = "عصبية"
                    },
                    new
                    {
                        Id = 5,
                        Name = "Pediatrics",
                        ConsultationFee = 110m,
                        IsActive = true,
                        Description = "أطفال"
                    },
                    new
                    {
                        Id = 6,
                        Name = "General Medicine",
                        ConsultationFee = 100m,
                        IsActive = true,
                        Description = "طب عام"
                    }
                );
#pragma warning restore 612, 618
            });
    }
    }
}