// <auto-generated />
using System;
using HCMS4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCMS4.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506154500_AddActivityLogMetadataColumns")]
    partial class AddActivityLogMetadataColumns
    {
    }
}
